[package]
name = "uqdev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.21"
clap = { version = "4.4", features = ["cargo", "string"] }
dirs = "5.0"
futures-util = "0.3"
nix = { version = "0.27", features = ["process", "signal", "term"] }
reqwest = { version = "0.11", features = ["json"] }
rmp-serde = "1.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.28", features = ["fs", "macros", "rt-multi-thread", "signal", "sync", "time"] }
tokio-tungstenite = "*"
toml = "0.8"
uqbar_process_lib = { git = "ssh://git@github.com/uqbar-dao/process_lib.git", rev = "77ebb26" }
walkdir = "2.4"
zip = "0.6"

[[bin]]
name = "uqdev"
path = "src/main.rs"
